In [1]:
import numpy as np

In [164]:
def check_horizontal(board):

    n = board.shape[0]
    
    m = board.shape[1]
    
    # check horizontal
    for i in range(n):
        curr_piece = board[i][0]
        count = 1
        for j in range(1,m):
            
            next_piece = board[i][j]
            
            if (curr_piece == 0) or (curr_piece != next_piece):
                count = 1
                curr_piece = next_piece
                continue
                
            if curr_piece == next_piece:
                count += 1
                curr_piece = next_piece
                if count == 4:
                    return curr_piece
                continue
                
    return 0

In [179]:
def check_winner_new(board):
    
    # check horizontal 
    c = check_horizontal(board)
    
    if c != 0:
        return c
    
    # check vertical 
    c = check_horizontal(board.T)
    
    if c!= 0:
        return c
    
    # check diagonal top left to bottom right
    for i in range(board.shape[0]):
        diag = np.diagonal(board,i,axis1=1,axis2=0)
        
        diag = diag.reshape((1,len(diag)))
        
        c = check_horizontal(diag)
        
        print(c)
        
        if c: return c
        
    # check diagonal top right to bottom left
    for j in range(board.shape[1]):
        
        diag = np.diagonal(board,j)
        
        diag = diag.reshape((1,len(diag)))

        c = check_horizontal(diag)
        
        print(c)
        
        if c: return c
    
    
    # check for draw
    num_zeros = np.where(board == 0)

    if len(num_zeros[0]) == 0:
        # we have played to this point without a winner and board is full
        return -1
    
    # no winners
    return 0

    

In [180]:
check_winner_new(board)

0
0
0
0
0
0
0
0
0
0
0
0
0


0

In [127]:
def check_winner(board):
    #assert type(board) == np.array
    assert board.shape == (6,7)
    
    n = board.shape[0]
    m = board.shape[1]
    
    # check horizontal
    for i in range(n):
        curr_piece = board[i][0]
        count = 1
        for j in range(1,m):
            
            next_piece = board[i][j]
            
            if (curr_piece == 0) or (curr_piece != next_piece):
                count = 1
                curr_piece = next_piece
                continue
                
            if curr_piece == next_piece:
                count += 1
                curr_piece = next_piece
                if count == 4:
                    return curr_piece
                continue
                
    # check vertical
    for i in range(m):
        curr_piece = board[0][i]
        count = 1
        for j in range(1,n):     
            next_piece = board[j][i]
            
            if (curr_piece == 0) or (curr_piece != next_piece):
                count = 1
                curr_piece = next_piece
                continue
                
            if curr_piece == next_piece:
                count += 1
                curr_piece = next_piece
                if count == 4:
                    return curr_piece
                continue
                
    # check diagnol first direction
    for i in range(n):
        # start top left corner
        curr_piece_1 = board[i][0]
        curr_piece_2 = board[i][-1]
        
        dist = np.abs(i - n) + 1
        if dist < 4:
            continue
        
        count1 = 1
        count2 = 1
        
        ii = i

        for j in range(1,dist - 1):
            
            next_piece_1 = board[ii + 1][j]
            next_piece_2 = board[ii + 1][-(j + 1)]
            
            print(f'ii = {ii} , j = {-j} , curr2 = {curr_piece_2}, next2 = {next_piece_2}, count1 = {count2}')
            
            if (curr_piece_1 == 0) or (curr_piece_1 != next_piece_1):
                count1 = 1
                
            if (curr_piece_2 == 0) or (curr_piece_2 != next_piece_2):
                count2 = 1
                
            if curr_piece_1 == next_piece_1:
                
                count1 += 1
                
                if count1 == 4:
                    return curr_piece_1
                
            if curr_piece_2 == next_piece_2:
                
                count2 += 1
                
                if count2 == 4:
                    return curr_piece_2
                
                
            curr_piece_1 = next_piece_1
            curr_piece_2 = next_piece_2
            ii += 1
            
        # check diagnol first direction
    for i in range(1,m - 1):
        # start top left corner
        curr_piece_1 = board[i][0]
        curr_piece_2 = board[i][-1]
        
        dist = np.abs(i - m) + 1
        if dist < 4:
            continue
        
        count1 = 1
        count2 = 1
        
        ii = i

        for j in range(1,dist - 1):
            
            next_piece_1 = board[ii + 1][j]
            next_piece_2 = board[ii + 1][-(j + 1)]
            
            print(f'ii = {ii} , j = {-j} , curr2 = {curr_piece_2}, next2 = {next_piece_2}, count1 = {count2}')
            
            if (curr_piece_1 == 0) or (curr_piece_1 != next_piece_1):
                count1 = 1
                
            if (curr_piece_2 == 0) or (curr_piece_2 != next_piece_2):
                count2 = 1
                
            if curr_piece_1 == next_piece_1:
                
                count1 += 1
                
                if count1 == 4:
                    return curr_piece_1
                
            if curr_piece_2 == next_piece_2:
                
                count2 += 1
                
                if count2 == 4:
                    return curr_piece_2
                
                
            curr_piece_1 = next_piece_1
            curr_piece_2 = next_piece_2
            ii += 1
        
        
                
    # check for draw
    num_zeros = np.where(board == 0)
    if len(num_zeros[0]) == 0:
        # we have played to this point without a winner and board is full
        return -1
                
    return 0
            
            

In [209]:
board = np.array([
        [0, 0, 3, 0, 2, 0, 0],
        [0, 0, 0, 0, 0, 2, 0],
        [3, 0, 0, 0, 0, 0, 2],
        [0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 1, 0],
        [0, 1, 0, 0, 1, 0, 0],
    ])

In [220]:
legal_play = np.where(board[:,1] == 3)

In [221]:
len(legal_play[0])d

0

In [215]:
board[legal_play,1] = 1

In [216]:
board

array([[0, 0, 3, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 2, 0],
       [3, 0, 0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 1, 0, 0]])

In [207]:
np.flip(board,axis=1)

array([[0, 0, 2, 0, 3, 0, 0],
       [0, 2, 0, 0, 0, 3, 0],
       [2, 0, 0, 0, 0, 0, 3],
       [1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0]])

In [200]:
np.diagonal(board.T,1,axis1=1,axis2=0)

array([0, 0, 0, 0, 1, 0])

In [203]:
np.diagonal(board,4)

array([2, 2, 2])

In [201]:
board.T

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0, 1],
       [0, 2, 0, 0, 1, 0],
       [0, 0, 2, 1, 0, 0]])

In [202]:
check_winner_new(board)

0
0
0
0
0
0
0
0
0
0
0
0
0


0

In [147]:
check_winner(board)

ii = 0 , j = -1 , curr2 = 1, next2 = 1, count1 = 1
ii = 1 , j = -2 , curr2 = 1, next2 = 1, count1 = 2
ii = 2 , j = -3 , curr2 = 1, next2 = 0, count1 = 3
ii = 3 , j = -4 , curr2 = 0, next2 = 1, count1 = 1
ii = 4 , j = -5 , curr2 = 1, next2 = 1, count1 = 1
ii = 1 , j = -1 , curr2 = 0, next2 = 0, count1 = 1
ii = 2 , j = -2 , curr2 = 0, next2 = 0, count1 = 2
ii = 3 , j = -3 , curr2 = 0, next2 = 2, count1 = 2
ii = 4 , j = -4 , curr2 = 2, next2 = 1, count1 = 1
ii = 2 , j = -1 , curr2 = 2, next2 = 2, count1 = 1
ii = 3 , j = -2 , curr2 = 2, next2 = 0, count1 = 2
ii = 4 , j = -3 , curr2 = 0, next2 = 2, count1 = 1
ii = 3 , j = -1 , curr2 = 0, next2 = 0, count1 = 1
ii = 4 , j = -2 , curr2 = 0, next2 = 0, count1 = 2


-1

In [189]:
np.diagonal?

Signature: np.diagonal(a, offset=0, axis1=0, axis2=1)
Docstring:
Return specified diagonals.

If `a` is 2-D, returns the diagonal of `a` with the given offset,
i.e., the collection of elements of the form ``a[i, i+offset]``.  If
`a` has more than two dimensions, then the axes specified by `axis1`
and `axis2` are used to determine the 2-D sub-array whose diagonal is
returned.  The shape of the resulting array can be determined by
removing `axis1` and `axis2` and appending an index to the right equal
to the size of the resulting diagonals.

In versions of NumPy prior to 1.7, this function always returned a new,
independent array containing a copy of the values in the diagonal.

In NumPy 1.7 and 1.8, it continues to return a copy of the diagonal,
but depending on this fact is deprecated. Writing to the resulting
array continues to work as it used to, but a FutureWarning is issued.

Starting in NumPy 1.9 it returns a read-only view on the original array.
Attempting to write to the resultin