In [13]:
import numpy as np

from vikingzero.agents.tictactoe_agents import TicTacMCTSNode
from vikingzero.environments.tictactoe_env import TicTacToe

How to generate all possible board states?

Brute force way: Go down the tree. State space is a tree
    
    Start from init board state:
        children = Get all children()
        for child in children:
            save child
            children = Get all children()
            
            for child in children:
                save child
                ......
                
            

In [2]:
states = {}
def process_node(node):
    
    #print("process node")
    #print(node.board)
    
    if hash(node) not in states:
        states[hash(node)] = node.board
        
    if node.is_terminal():
        #print("Terminal")
        return
    
    for child in node.get_children():
        #print("Childe")
        #print(child.board)
        process_node(child)

In [3]:
root_board = np.zeros((3,3))

In [4]:
root_node =  TicTacMCTSNode(TicTacToe(),root_board.flatten(),1, 0, root = True)

In [5]:
children = root_node.get_children()

In [6]:
for child in children:
    print(child.board)

[1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [7]:
process_node(root_node)

In [8]:
len(states)

5478

In [47]:
keys = list(states.keys())

In [52]:
hash(keys[0])

8451130094049736394

In [66]:
dict_path = "/Users/befeltingu/Documents/Github/VikingZeroDev/tests/tictactoe_states.npy"

In [68]:
np.save(dict_path,states)

In [69]:
load_dict = np.load(dict_path,allow_pickle='TRUE').item()

In [70]:
len(load_dict)

5478

In [71]:
type(load_dict)

dict

Want to use the state dict as way to have a more thourough tests for the progress of my agent. 

In [9]:
env = TicTacToe()

In [11]:
class Agent:
    def __init__(self,env):
        self.env = env
    
    def act(state):
        
        valid_actions = self.env.check_valid_actions(state)
        
        return np.random.choice(valid_actions)

In [4]:
state_dict_path = "/Users/befeltingu/Documents/Github/VikingZeroDev/tests/state_dict.npy"
minimax_save_path = "/Users/befeltingu/Documents/Github/VikingZeroDev/tests/minimax_state_actions.npy"

In [19]:
from vikingzero.utils import create_minimax_lookup, generate_tictactoe_state_dict

In [20]:
from vikingzero.agents.tictactoe_agents import TicTacToeMinMax

In [21]:
#state_dict = generate_tictactoe_state_dict()

In [22]:
import numpy as np

In [23]:
np.save(state_dict_path,state_dict)

In [24]:
def create_minimax_lookup(save_path,state_dict_path=""):

    env = TicTacToe()

    minimax_agent = TicTacToeMinMax(env,type="alphabeta")

    if len(state_dict_path) > 0:
        try:
            states = np.load(state_dict_path,allow_pickle=True).item()
        except:
            print("State dict path does not appear to be correct. Creating new state dict")
            pass

    else:
        states = generate_tictactoe_state_dict()


    minimax_actions = {}

    for k,v in states.items():

        valid_actions = env.valid_actions(v)

        if len(valid_actions) == 0:
            continue

        a = minimax_agent.act(v)

        minimax_actions[k] = list(a)

    np.save(save_path,states)


In [25]:
create_minimax_lookup(minimax_save_path, state_dict_path)

AttributeError: 'list' object has no attribute 'board'